/* ============================================================================
 * Marketing Ideas — Seed Data
 * ----------------------------------------------------------------------------
 * A curated library of marketing ideas. Each idea is tagged with the months it
 * is most relevant (1 = January ... 12 = December; an empty months array means
 * "evergreen / any time"), a channel/category, and effort/cost/impact ratings.
 *
 * User-specific state (status, notes, custom ideas) is layered on top of this
 * seed data at runtime and stored in localStorage — this file is never mutated.
 * ==========================================================================*/

const CATEGORIES = [
  { id: "social",       label: "Social Media",      icon: "📱", color: "#6366f1" },
  { id: "email",        label: "Email Marketing",   icon: "✉️", color: "#0ea5e9" },
  { id: "content",      label: "Content & Blog",    icon: "✍️", color: "#10b981" },
  { id: "seo",          label: "SEO",               icon: "🔍", color: "#22c55e" },
  { id: "paid",         label: "Paid Ads",          icon: "💰", color: "#f59e0b" },
  { id: "events",       label: "Events & Webinars", icon: "🎤", color: "#ec4899" },
  { id: "partnerships", label: "Partnerships",      icon: "🤝", color: "#8b5cf6" },
  { id: "pr",           label: "PR & Media",        icon: "📰", color: "#ef4444" },
  { id: "referral",     label: "Referral & Loyalty",icon: "🎁", color: "#f43f5e" },
  { id: "video",        label: "Video",             icon: "🎬", color: "#d946ef" },
  { id: "community",    label: "Community",         icon: "👥", color: "#14b8a6" },
  { id: "local",        label: "Local & In-Person", icon: "📍", color: "#84cc16" },
  { id: "seasonal",     label: "Seasonal & Holiday",icon: "🎉", color: "#fb923c" },
  { id: "product",      label: "Product & Launch",  icon: "🚀", color: "#3b82f6" },
];

const MONTH_NAMES = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

// Short, evocative theme for each month to inspire campaigns.
const MONTH_THEMES = [
  { name: "January",   theme: "Fresh starts, goals & New Year resolutions",        emoji: "❄️" },
  { name: "February",  theme: "Love, relationships & customer appreciation",        emoji: "💝" },
  { name: "March",     theme: "Spring renewal, growth & spring cleaning",           emoji: "🌱" },
  { name: "April",     theme: "Renewal, sustainability & playful campaigns",        emoji: "🌷" },
  { name: "May",       theme: "Outdoors, family & momentum building",               emoji: "🌸" },
  { name: "June",      theme: "Summer kickoff, mid-year reviews & pride",           emoji: "☀️" },
  { name: "July",      theme: "Vacation mode, freedom & summer sales",              emoji: "🏖️" },
  { name: "August",    theme: "Back-to-school prep & end-of-summer pushes",         emoji: "🎒" },
  { name: "September", theme: "Back to business, routines & fresh focus",           emoji: "🍂" },
  { name: "October",   theme: "Spooky season, urgency & Q4 planning",               emoji: "🎃" },
  { name: "November",  theme: "Gratitude, Black Friday & holiday ramp-up",          emoji: "🦃" },
  { name: "December",  theme: "Holidays, year-end reflection & gifting",            emoji: "🎄" },
];

const SEED_IDEAS = [
  // ---- JANUARY ----------------------------------------------------------
  { id: "jan-resolution-campaign", title: "“New Year, New You” campaign", category: "seasonal", months: [1],
    effort: "medium", cost: "low", impact: "high",
    description: "Tie your product to customers' fresh-start mindset. Bundle a goal-setting theme into emails, social, and a landing page.",
    tags: ["new year", "goals"] },
  { id: "jan-goal-content", title: "Publish a 'goals for the year' resource", category: "content", months: [1],
    effort: "medium", cost: "free", impact: "medium",
    description: "A planner, checklist, or template that helps your audience plan their year — gated for lead capture.",
    tags: ["lead magnet", "planning"] },
  { id: "jan-year-in-review", title: "Share last year's wins & roadmap", category: "social", months: [1],
    effort: "low", cost: "free", impact: "medium",
    description: "Transparency post: what you shipped, what customers achieved, and what's coming. Builds trust and momentum.",
    tags: ["transparency", "roadmap"] },
  { id: "jan-veganuary", title: "Tie into Veganuary / Dry January trends", category: "social", months: [1],
    effort: "low", cost: "free", impact: "medium",
    description: "If relevant to your brand, ride trending January health movements with helpful, on-theme content.",
    tags: ["trend", "health"] },

  // ---- FEBRUARY ---------------------------------------------------------
  { id: "feb-valentines", title: "Valentine's Day promotion", category: "seasonal", months: [2],
    effort: "medium", cost: "low", impact: "high",
    description: "Couples/gift bundle, 'treat yourself' angle, or a love-themed discount. Works even for B2B with a playful twist.",
    tags: ["valentines", "promo"] },
  { id: "feb-customer-love", title: "Customer appreciation week", category: "referral", months: [2],
    effort: "medium", cost: "low", impact: "high",
    description: "Send a heartfelt thank-you, exclusive perk, or handwritten note to loyal customers. Spotlight them publicly.",
    tags: ["loyalty", "appreciation"] },
  { id: "feb-galentines", title: "Galentine's / friendship referral push", category: "referral", months: [2],
    effort: "low", cost: "low", impact: "medium",
    description: "“Refer a friend” campaign framed around sharing something you love with the people you love.",
    tags: ["referral", "friends"] },

  // ---- MARCH ------------------------------------------------------------
  { id: "mar-spring-clean", title: "Spring cleaning / declutter campaign", category: "seasonal", months: [3],
    effort: "medium", cost: "low", impact: "medium",
    description: "Position your product as part of a fresh-start spring refresh. Great for productivity, home, finance, and wellness brands.",
    tags: ["spring", "refresh"] },
  { id: "mar-womens-day", title: "International Women's Day feature", category: "content", months: [3],
    effort: "medium", cost: "free", impact: "medium",
    description: "Spotlight women on your team or in your community; partner with a relevant cause. Authenticity matters here.",
    tags: ["IWD", "values"] },
  { id: "mar-q1-review", title: "Q1 results & lessons-learned post", category: "content", months: [3],
    effort: "low", cost: "free", impact: "low",
    description: "Build-in-public recap that doubles as social proof and keeps your audience engaged.",
    tags: ["build in public"] },

  // ---- APRIL ------------------------------------------------------------
  { id: "apr-fools", title: "April Fools' brand stunt", category: "social", months: [4],
    effort: "medium", cost: "free", impact: "medium",
    description: "A tasteful, on-brand joke product or announcement. High virality potential if it lands — keep it clearly fake.",
    tags: ["viral", "fun"] },
  { id: "apr-earth-day", title: "Earth Day sustainability story", category: "pr", months: [4],
    effort: "medium", cost: "low", impact: "medium",
    description: "Share genuine sustainability efforts or launch a green initiative. Avoid greenwashing — back claims with specifics.",
    tags: ["sustainability", "earth day"] },
  { id: "apr-spring-sale", title: "Spring sale event", category: "paid", months: [4, 5],
    effort: "medium", cost: "medium", impact: "high",
    description: "Limited-time spring promotion with paid retargeting to drive urgency before the summer slowdown.",
    tags: ["sale", "promo"] },

  // ---- MAY --------------------------------------------------------------
  { id: "may-mothers-day", title: "Mother's Day gift guide", category: "content", months: [5],
    effort: "medium", cost: "low", impact: "high",
    description: "Curated gift guide or gift-card push. Promote early (gifting decisions happen ~2 weeks out).",
    tags: ["mothers day", "gifting"] },
  { id: "may-mid-year-check", title: "“Halfway to your goals” email", category: "email", months: [5, 6],
    effort: "low", cost: "free", impact: "medium",
    description: "Re-engage subscribers by helping them recommit to goals they set in January. Strong reactivation angle.",
    tags: ["reactivation"] },
  { id: "may-graduation", title: "Graduation season promotion", category: "seasonal", months: [5, 6],
    effort: "medium", cost: "low", impact: "medium",
    description: "Target grads and gift-buyers. Works for tech, apparel, finance, and education brands.",
    tags: ["graduation", "gifting"] },

  // ---- JUNE -------------------------------------------------------------
  { id: "jun-summer-kickoff", title: "Summer kickoff campaign", category: "seasonal", months: [6],
    effort: "medium", cost: "low", impact: "medium",
    description: "Refresh creative with summer themes; launch a seasonal product line or limited edition.",
    tags: ["summer"] },
  { id: "jun-pride", title: "Pride Month support (authentic)", category: "community", months: [6],
    effort: "medium", cost: "low", impact: "medium",
    description: "Show genuine, year-round support — partner with LGBTQ+ orgs and put substance behind the rainbow.",
    tags: ["pride", "values"] },
  { id: "jun-mid-year-report", title: "Mid-year 'state of the industry' report", category: "content", months: [6, 7],
    effort: "high", cost: "low", impact: "high",
    description: "Original data report that earns backlinks, press, and authority. Repurpose into a webinar and social series.",
    tags: ["thought leadership", "data"] },

  // ---- JULY -------------------------------------------------------------
  { id: "jul-summer-sale", title: "Christmas in July / summer flash sale", category: "paid", months: [7],
    effort: "medium", cost: "medium", impact: "high",
    description: "Combat the summer slump with a surprise flash sale. Lean into the playful 'Christmas in July' hook.",
    tags: ["sale", "flash"] },
  { id: "jul-ugc-contest", title: "Summer user-generated content contest", category: "social", months: [7, 8],
    effort: "medium", cost: "low", impact: "high",
    description: "Run a photo/video contest with a branded hashtag and prize. Fills your content pipeline with social proof.",
    tags: ["UGC", "contest"] },

  // ---- AUGUST -----------------------------------------------------------
  { id: "aug-back-to-school", title: "Back-to-school campaign", category: "seasonal", months: [8, 9],
    effort: "medium", cost: "medium", impact: "high",
    description: "Major retail moment. Position your product around routines, productivity, and fresh starts for the new season.",
    tags: ["back to school"] },
  { id: "aug-end-summer", title: "End-of-summer clearance", category: "paid", months: [8],
    effort: "low", cost: "medium", impact: "medium",
    description: "Clear seasonal inventory and capture last-minute summer spenders before attention shifts to fall.",
    tags: ["clearance", "sale"] },

  // ---- SEPTEMBER --------------------------------------------------------
  { id: "sep-fresh-start", title: "“September reset” productivity push", category: "content", months: [9],
    effort: "medium", cost: "free", impact: "medium",
    description: "September is the unofficial second New Year. Help audiences rebuild routines and focus — strong for B2B and SaaS.",
    tags: ["reset", "productivity"] },
  { id: "sep-q4-planning", title: "Publish a Q4 / holiday planning guide", category: "content", months: [9],
    effort: "medium", cost: "free", impact: "medium",
    description: "Help your B2B customers plan their holiday marketing. Positions you as a helpful expert ahead of peak season.",
    tags: ["planning", "B2B"] },

  // ---- OCTOBER ----------------------------------------------------------
  { id: "oct-halloween", title: "Halloween-themed campaign", category: "seasonal", months: [10],
    effort: "medium", cost: "low", impact: "medium",
    description: "Spooky creative, limited-edition products, or a costume/UGC contest. Playful brands win big here.",
    tags: ["halloween"] },
  { id: "oct-bf-warmup", title: "Build your Black Friday early-access list", category: "email", months: [10],
    effort: "medium", cost: "low", impact: "high",
    description: "Start a VIP waitlist for BFCM deals now. Early-access signups convert far better when the sale hits.",
    tags: ["black friday", "list building"] },
  { id: "oct-cybersecurity", title: "Cybersecurity Awareness Month content", category: "content", months: [10],
    effort: "low", cost: "free", impact: "low",
    description: "If relevant, ride the awareness month with tips and trust-building content.",
    tags: ["awareness"] },

  // ---- NOVEMBER ---------------------------------------------------------
  { id: "nov-black-friday", title: "Black Friday / Cyber Monday blitz", category: "paid", months: [11],
    effort: "high", cost: "high", impact: "high",
    description: "Your biggest revenue moment. Plan tiered offers, email sequences, paid retargeting, and abandoned-cart flows weeks ahead.",
    tags: ["BFCM", "sale"] },
  { id: "nov-small-biz-sat", title: "Small Business Saturday spotlight", category: "local", months: [11],
    effort: "low", cost: "low", impact: "medium",
    description: "Lean into shop-local sentiment. Cross-promote with other local businesses for a bundled offer.",
    tags: ["local", "small business"] },
  { id: "nov-gratitude", title: "Thanksgiving gratitude message", category: "email", months: [11],
    effort: "low", cost: "free", impact: "medium",
    description: "A no-strings thank-you to your audience. Builds goodwill amid the BFCM noise — no hard sell.",
    tags: ["gratitude", "brand"] },

  // ---- DECEMBER ---------------------------------------------------------
  { id: "dec-holiday-gift-guide", title: "Holiday gift guide", category: "content", months: [12],
    effort: "medium", cost: "low", impact: "high",
    description: "Curated, shoppable gift guide segmented by recipient or budget. A perennial top performer for traffic and sales.",
    tags: ["holiday", "gifting"] },
  { id: "dec-last-minute", title: "Last-minute & gift-card promo", category: "paid", months: [12],
    effort: "low", cost: "medium", impact: "high",
    description: "Capture procrastinators with shipping deadlines and instant-delivery gift cards.",
    tags: ["holiday", "gift card"] },
  { id: "dec-year-in-review", title: "Personalized 'year in review' for customers", category: "email", months: [12],
    effort: "high", cost: "low", impact: "high",
    description: "Spotify-Wrapped-style recap of each customer's year with you. Highly shareable and great for retention.",
    tags: ["personalization", "retention"] },
  { id: "dec-giving", title: "End-of-year giving / charity tie-in", category: "pr", months: [12],
    effort: "medium", cost: "medium", impact: "medium",
    description: "Donate a portion of December sales to a cause your audience cares about. Aligns brand with generosity.",
    tags: ["charity", "values"] },

  // ---- EVERGREEN (any month) -------------------------------------------
  { id: "ever-newsletter", title: "Launch or revive a regular newsletter", category: "email", months: [],
    effort: "medium", cost: "free", impact: "high",
    description: "Owned audience you control. Consistency beats perfection — pick a cadence you can sustain.",
    tags: ["owned media", "retention"] },
  { id: "ever-case-study", title: "Publish a customer case study", category: "content", months: [],
    effort: "medium", cost: "low", impact: "high",
    description: "Story-driven proof of results. One of the highest-converting assets for B2B and considered purchases.",
    tags: ["social proof", "B2B"] },
  { id: "ever-testimonials", title: "Collect & showcase testimonials", category: "social", months: [],
    effort: "low", cost: "free", impact: "high",
    description: "Ask happy customers for a quick quote or video. Sprinkle proof across your site, ads, and emails.",
    tags: ["social proof"] },
  { id: "ever-referral-program", title: "Set up a referral program", category: "referral", months: [],
    effort: "high", cost: "medium", impact: "high",
    description: "Turn customers into a growth channel with a double-sided incentive. Compounds over time.",
    tags: ["growth", "loyalty"] },
  { id: "ever-seo-pillar", title: "Write an SEO pillar page", category: "seo", months: [],
    effort: "high", cost: "free", impact: "high",
    description: "A comprehensive, evergreen guide targeting a high-intent keyword. The backbone of organic growth.",
    tags: ["SEO", "evergreen"] },
  { id: "ever-keyword-audit", title: "Run a keyword & content gap audit", category: "seo", months: [],
    effort: "medium", cost: "low", impact: "medium",
    description: "Find what your audience searches for and where competitors outrank you. Builds your content roadmap.",
    tags: ["SEO", "research"] },
  { id: "ever-webinar", title: "Host a webinar or live workshop", category: "events", months: [],
    effort: "high", cost: "low", impact: "high",
    description: "Educate, generate leads, and demo your expertise live. Repurpose the recording into many assets.",
    tags: ["lead gen", "education"] },
  { id: "ever-podcast-guest", title: "Pitch yourself as a podcast guest", category: "pr", months: [],
    effort: "medium", cost: "free", impact: "medium",
    description: "Borrow other audiences. Build a list of relevant shows and pitch a specific, valuable topic.",
    tags: ["PR", "borrowed audience"] },
  { id: "ever-influencer", title: "Partner with a micro-influencer", category: "partnerships", months: [],
    effort: "medium", cost: "medium", impact: "medium",
    description: "Micro-influencers (5k–50k) often beat celebrities on engagement and trust per dollar.",
    tags: ["influencer", "partnerships"] },
  { id: "ever-cobrand", title: "Run a co-marketing campaign with a partner", category: "partnerships", months: [],
    effort: "high", cost: "low", impact: "high",
    description: "Team up with a non-competing brand that shares your audience — co-host, co-create, cross-promote.",
    tags: ["co-marketing"] },
  { id: "ever-short-video", title: "Start a short-form video series (Reels/TikTok/Shorts)", category: "video", months: [],
    effort: "high", cost: "low", impact: "high",
    description: "The highest-reach organic format right now. Batch-film, post consistently, double down on what works.",
    tags: ["video", "organic reach"] },
  { id: "ever-behind-scenes", title: "Share behind-the-scenes content", category: "social", months: [],
    effort: "low", cost: "free", impact: "medium",
    description: "Humanize your brand with the people, process, and culture behind it. Builds connection and trust.",
    tags: ["brand", "authentic"] },
  { id: "ever-community-group", title: "Build a community (Slack/Discord/Circle)", category: "community", months: [],
    effort: "high", cost: "low", impact: "high",
    description: "A space for customers to connect deepens loyalty and creates a moat. Requires ongoing nurturing.",
    tags: ["community", "retention"] },
  { id: "ever-loyalty-points", title: "Launch a loyalty / points program", category: "referral", months: [],
    effort: "high", cost: "medium", impact: "high",
    description: "Reward repeat purchases and engagement. Boosts lifetime value and gives a reason to return.",
    tags: ["loyalty", "LTV"] },
  { id: "ever-retargeting", title: "Set up retargeting ads", category: "paid", months: [],
    effort: "medium", cost: "medium", impact: "high",
    description: "Re-engage site visitors who didn't convert. Usually the highest-ROAS paid campaign you can run.",
    tags: ["paid", "ROAS"] },
  { id: "ever-abandoned-cart", title: "Automate an abandoned-cart / abandoned-trial flow", category: "email", months: [],
    effort: "medium", cost: "low", impact: "high",
    description: "Recover lost revenue on autopilot with a 2–3 email sequence. Set once, earns forever.",
    tags: ["automation", "recovery"] },
  { id: "ever-welcome-series", title: "Build a welcome email series", category: "email", months: [],
    effort: "medium", cost: "free", impact: "high",
    description: "First impressions convert. Onboard new subscribers with a 3–5 email sequence that delivers value and sells.",
    tags: ["automation", "onboarding"] },
  { id: "ever-lead-magnet", title: "Create a lead magnet", category: "content", months: [],
    effort: "medium", cost: "free", impact: "high",
    description: "A free, high-value asset (template, checklist, mini-course) traded for an email. Fuels list growth.",
    tags: ["lead gen", "list building"] },
  { id: "ever-local-seo", title: "Optimize your Google Business Profile", category: "local", months: [],
    effort: "low", cost: "free", impact: "high",
    description: "For local businesses, this is the highest-leverage free move. Complete profile, photos, posts, and reviews.",
    tags: ["local SEO", "free"] },
  { id: "ever-review-requests", title: "Systematize review requests", category: "local", months: [],
    effort: "low", cost: "free", impact: "high",
    description: "Ask every happy customer for a review at the right moment. Reviews drive both trust and local ranking.",
    tags: ["reviews", "social proof"] },
  { id: "ever-repurpose", title: "Repurpose one asset into ten", category: "content", months: [],
    effort: "low", cost: "free", impact: "medium",
    description: "Turn a blog post into a thread, carousel, video, email, and quote graphics. Maximize every piece you make.",
    tags: ["efficiency", "repurposing"] },
  { id: "ever-survey", title: "Run a customer survey", category: "content", months: [],
    effort: "low", cost: "low", impact: "medium",
    description: "Mine customers for messaging, testimonials, and product ideas. Insights compound across every channel.",
    tags: ["research", "voice of customer"] },
  { id: "ever-product-launch", title: "Plan a product launch sequence", category: "product", months: [],
    effort: "high", cost: "low", impact: "high",
    description: "Tease → reveal → launch → social proof. A structured runway dramatically outperforms a single announcement.",
    tags: ["launch", "product"] },
  { id: "ever-free-tool", title: "Build a free tool or calculator", category: "product", months: [],
    effort: "high", cost: "medium", impact: "high",
    description: "A useful free tool attracts links, leads, and search traffic on autopilot. Powerful evergreen acquisition.",
    tags: ["growth", "SEO", "free tool"] },
  { id: "ever-affiliate", title: "Start an affiliate program", category: "partnerships", months: [],
    effort: "high", cost: "low", impact: "medium",
    description: "Pay only for results. Recruit creators and partners to sell on your behalf for a commission.",
    tags: ["affiliate", "growth"] },
  { id: "ever-pop-up", title: "Host a pop-up or local event", category: "events", months: [],
    effort: "high", cost: "medium", impact: "medium",
    description: "Real-world presence builds memorable connections and earns local press and social content.",
    tags: ["local", "experiential"] },
  { id: "ever-press-kit", title: "Create a press kit & media list", category: "pr", months: [],
    effort: "medium", cost: "free", impact: "low",
    description: "Make it effortless for journalists to cover you. Build a targeted list and a ready-to-use kit.",
    tags: ["PR", "media"] },
  { id: "ever-faq-content", title: "Turn customer questions into content", category: "seo", months: [],
    effort: "low", cost: "free", impact: "medium",
    description: "Answer every real question your customers ask. Captures high-intent search and reduces support load.",
    tags: ["SEO", "support"] },
];
