/* ============================================================================
 * Henley Studio — Marketing Ideas (Seed Data)
 * ----------------------------------------------------------------------------
 * Tailored for a luxury PORTRAIT / HEADSHOT / PERSONAL BRANDING / BOUDOIR
 * studio based in South East Brisbane, Australia.
 *
 * NOTE ON SEASONS: months are Southern-Hemisphere / Australian aware.
 *   Summer = Dec–Feb · Autumn = Mar–May · Winter = Jun–Aug · Spring = Sep–Nov
 * Key AU dates baked in: Australia Day (Jan), Mother's Day (May), EOFY/tax
 * time (Jun–Jul), Father's Day (first Sun of SEPTEMBER in AU), Spring Racing
 * Carnival (Oct–Nov), Black Friday (Nov), summer Christmas (Dec).
 *
 * Each idea is tagged with relevant months (1=Jan…12=Dec; [] = evergreen),
 * a channel/category, and effort/cost/impact ratings. User state (status,
 * notes, custom ideas) is layered on at runtime and saved to localStorage —
 * this file is never mutated.
 * ==========================================================================*/

const CATEGORIES = [
  { id: "social",       label: "Social Media",        icon: "📱", color: "#6366f1" },
  { id: "email",        label: "Email Marketing",     icon: "✉️", color: "#0ea5e9" },
  { id: "content",      label: "Blog & Content",      icon: "✍️", color: "#10b981" },
  { id: "seo",          label: "SEO & Website",       icon: "🔍", color: "#22c55e" },
  { id: "paid",         label: "Paid Ads",            icon: "💰", color: "#f59e0b" },
  { id: "offers",       label: "Sessions & Offers",   icon: "📸", color: "#ec4899" },
  { id: "partnerships", label: "Collabs & Partners",  icon: "🤝", color: "#8b5cf6" },
  { id: "pr",           label: "PR & Features",       icon: "📰", color: "#ef4444" },
  { id: "referral",     label: "Referrals & Loyalty", icon: "🎁", color: "#f43f5e" },
  { id: "video",        label: "Video & Reels",       icon: "🎬", color: "#d946ef" },
  { id: "community",    label: "Community & Network",  icon: "👥", color: "#14b8a6" },
  { id: "local",        label: "Local Brisbane",      icon: "📍", color: "#84cc16" },
  { id: "client",       label: "Client Experience",   icon: "💎", color: "#06b6d4" },
  { id: "seasonal",     label: "Seasonal & Holiday",  icon: "🎉", color: "#fb923c" },
];

const MONTH_NAMES = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

// Australian-season-aware theme for each month.
const MONTH_THEMES = [
  { name: "January",   theme: "Summer · fresh-start headshots & New Year goals",      emoji: "☀️" },
  { name: "February",  theme: "Back-to-business branding & Valentine's boudoir",      emoji: "💝" },
  { name: "March",     theme: "Autumn light · Women's Day & Q1 refresh",              emoji: "🍂" },
  { name: "April",     theme: "Autumn tones · Easter & school-holiday family",        emoji: "🌾" },
  { name: "May",       theme: "Mother's Day portraits & gift vouchers",              emoji: "💐" },
  { name: "June",      theme: "EOFY · tax-deductible branding shoots (June 30)",      emoji: "📊" },
  { name: "July",      theme: "New financial year · winter studio glam",             emoji: "❄️" },
  { name: "August",    theme: "Winter · Father's Day prep (AU = early Sept)",         emoji: "🧥" },
  { name: "September", theme: "Spring + AU Father's Day · LinkedIn refresh",          emoji: "🌸" },
  { name: "October",   theme: "Spring Racing glam & end-of-year event prep",         emoji: "🏇" },
  { name: "November",  theme: "Black Friday vouchers & party-season headshots",       emoji: "🛍️" },
  { name: "December",  theme: "Summer Christmas · gift vouchers & family time",       emoji: "🎄" },
];

const SEED_IDEAS = [
  // ---- JANUARY (Summer) -------------------------------------------------
  { id: "jan-new-year-headshots", title: "“New Year, New Headshots” campaign", category: "offers", months: [1],
    effort: "medium", cost: "low", impact: "high",
    description: "Tap the fresh-start mindset — promote updated professional headshots and personal-branding sessions for the year ahead. Bundle into email + IG.",
    tags: ["new year", "headshots"] },
  { id: "jan-linkedin-refresh", title: "“Refresh your LinkedIn for 2026” push", category: "social", months: [1],
    effort: "low", cost: "free", impact: "medium",
    description: "Job-hunting and goal-setting peak in January. Post a before/after and remind professionals an outdated headshot costs them opportunities.",
    tags: ["linkedin", "professionals"] },
  { id: "jan-australia-day", title: "Australia Day long-weekend mini-sessions", category: "seasonal", months: [1],
    effort: "medium", cost: "low", impact: "medium",
    description: "Offer relaxed summer mini-sessions around the public holiday while people are off work and in a sunny, social mood.",
    tags: ["australia day", "mini session"] },
  { id: "jan-year-goals-bts", title: "Share your studio goals for the year", category: "social", months: [1],
    effort: "low", cost: "free", impact: "low",
    description: "A personal, behind-the-brand post about what's coming at Henley Studio this year. Builds connection and keeps you top of mind.",
    tags: ["behind the scenes", "brand"] },

  // ---- FEBRUARY (Summer) ------------------------------------------------
  { id: "feb-valentines-boudoir", title: "Valentine's boudoir experience", category: "offers", months: [2],
    effort: "medium", cost: "low", impact: "high",
    description: "Promote an empowering boudoir session as a gift (for a partner — or themselves). Lean into the luxury experience: hair, makeup, guided posing.",
    tags: ["boudoir", "valentines"] },
  { id: "feb-galentines", title: "Galentine's boudoir / portrait party", category: "offers", months: [2],
    effort: "medium", cost: "low", impact: "medium",
    description: "A group booking for friends — confidence-boosting portraits with bubbles, hair & makeup. Great word-of-mouth and social content.",
    tags: ["boudoir", "group", "friends"] },
  { id: "feb-back-to-business", title: "“Back to business” branding refresh", category: "offers", months: [2],
    effort: "medium", cost: "low", impact: "high",
    description: "Businesses are back in full swing after summer. Pitch personal-branding sessions for owners launching new offers this year.",
    tags: ["personal branding", "B2B"] },

  // ---- MARCH (Autumn) ---------------------------------------------------
  { id: "mar-womens-day", title: "International Women's Day feature series", category: "content", months: [3],
    effort: "medium", cost: "free", impact: "medium",
    description: "Spotlight women business owners you've photographed. Celebrates clients, shows your work, and aligns with your empowering brand.",
    tags: ["IWD", "women in business"] },
  { id: "mar-autumn-tones", title: "Autumn-toned styled session promo", category: "social", months: [3, 4, 5],
    effort: "low", cost: "free", impact: "medium",
    description: "Show off warm autumn wardrobe palettes and lighting. Position now as the perfect season for rich, timeless portraits.",
    tags: ["autumn", "styling"] },
  { id: "mar-eofy-teaser", title: "Early EOFY teaser for business clients", category: "email", months: [3],
    effort: "low", cost: "free", impact: "medium",
    description: "Plant the seed: a branding shoot before June 30 can be a tax-deductible business expense. Get on their radar before the rush.",
    tags: ["EOFY", "tax", "B2B"] },

  // ---- APRIL (Autumn) ---------------------------------------------------
  { id: "apr-easter-family", title: "Easter / school-holiday family portraits", category: "offers", months: [4],
    effort: "medium", cost: "low", impact: "medium",
    description: "Families are together and off work over the Easter break — offer relaxed family or generational portrait mini-sessions.",
    tags: ["family", "easter", "school holidays"] },
  { id: "apr-mothers-day-early", title: "Open Mother's Day gift-voucher sales", category: "offers", months: [4],
    effort: "low", cost: "low", impact: "high",
    description: "Mother's Day (mid-May in AU) gifting decisions start now. Launch beautiful gift vouchers for portrait & 'mum and me' sessions early.",
    tags: ["mothers day", "gift voucher"] },
  { id: "apr-whatToWear-guide", title: "Publish a 'what to wear' style guide", category: "content", months: [4],
    effort: "medium", cost: "free", impact: "medium",
    description: "An evergreen blog + downloadable guide on outfits for portraits/personal branding. Removes booking hesitation and captures leads.",
    tags: ["lead magnet", "styling", "SEO"] },

  // ---- MAY (Autumn) -----------------------------------------------------
  { id: "may-mothers-day", title: "Mother's Day portrait campaign", category: "seasonal", months: [5],
    effort: "medium", cost: "low", impact: "high",
    description: "Your biggest autumn moment. Promote 'mum and me' sessions and last-minute gift vouchers. Highlight the hair-and-makeup pampering angle.",
    tags: ["mothers day", "portraits"] },
  { id: "may-mum-and-me", title: "“Mum & Me” generational session offer", category: "offers", months: [5],
    effort: "medium", cost: "low", impact: "medium",
    description: "Multi-generational portraits (grandma, mum, kids). Emotional, high-value, and very shareable on social.",
    tags: ["family", "generational"] },
  { id: "may-eofy-countdown", title: "EOFY countdown for branding shoots", category: "email", months: [5],
    effort: "low", cost: "low", impact: "high",
    description: "“Book before June 30” email sequence to business owners — refresh your brand imagery and claim it this financial year.",
    tags: ["EOFY", "tax", "B2B"] },

  // ---- JUNE (Winter · EOFY) --------------------------------------------
  { id: "jun-eofy-branding", title: "EOFY tax-deductible branding blitz", category: "offers", months: [6],
    effort: "high", cost: "medium", impact: "high",
    description: "The standout AU opportunity: personal-branding & headshot packages businesses can book and claim before June 30. Push hard across email + ads.",
    tags: ["EOFY", "tax", "personal branding", "B2B"] },
  { id: "jun-corporate-headshots", title: "Corporate / team headshot outreach", category: "partnerships", months: [6],
    effort: "high", cost: "low", impact: "high",
    description: "Email/DM local Brisbane businesses about on-brand team headshots before EOFY. One booking = many sessions and recurring revenue.",
    tags: ["corporate", "B2B", "teams"] },
  { id: "jun-winter-studio", title: "Promote the cosy winter studio experience", category: "social", months: [6, 7, 8],
    effort: "low", cost: "free", impact: "medium",
    description: "Reframe winter as ideal: warm, controlled studio lighting, hair & makeup, no weather worries. Counter the seasonal booking dip.",
    tags: ["winter", "studio"] },

  // ---- JULY (Winter · New FY) ------------------------------------------
  { id: "jul-new-fy", title: "New financial year 'invest in your brand' push", category: "offers", months: [7],
    effort: "medium", cost: "low", impact: "high",
    description: "Fresh budgets, fresh goals. Position a branding shoot as the first smart investment of the new financial year for business owners.",
    tags: ["new financial year", "B2B"] },
  { id: "jul-model-call", title: "Run a personal-branding model call", category: "offers", months: [7],
    effort: "medium", cost: "low", impact: "medium",
    description: "Fill quieter winter weeks: offer discounted sessions to ideal-client business owners in exchange for content rights & testimonials.",
    tags: ["model call", "portfolio", "winter"] },
  { id: "jul-christmas-in-july", title: "Christmas in July voucher offer", category: "seasonal", months: [7],
    effort: "low", cost: "low", impact: "medium",
    description: "Playful mid-year promotion — bonus print credit or a voucher upgrade on sessions booked this month.",
    tags: ["promo", "winter"] },

  // ---- AUGUST (Winter) --------------------------------------------------
  { id: "aug-fathers-day-vouchers", title: "Father's Day gift vouchers (book early!)", category: "offers", months: [8],
    effort: "low", cost: "low", impact: "high",
    description: "AU Father's Day is the first Sunday of September — sell vouchers and 'dad & me' / family sessions NOW so they're ready in time.",
    tags: ["fathers day", "gift voucher"] },
  { id: "aug-spring-waitlist", title: "Open a spring session waitlist", category: "email", months: [8],
    effort: "low", cost: "free", impact: "medium",
    description: "Build anticipation for spring bookings. A VIP waitlist gives early access and primes demand before the busy Sept–Nov run.",
    tags: ["waitlist", "spring"] },
  { id: "aug-personal-brand-content", title: "Educate on why personal branding photos matter", category: "content", months: [8],
    effort: "medium", cost: "free", impact: "medium",
    description: "A blog/reel on how professional imagery wins clients & trust. Sells the 'why' before people are ready for the 'who'.",
    tags: ["personal branding", "education"] },

  // ---- SEPTEMBER (Spring · AU Father's Day) ----------------------------
  { id: "sep-fathers-day", title: "Father's Day portraits & last-minute vouchers", category: "seasonal", months: [9],
    effort: "medium", cost: "low", impact: "high",
    description: "First Sunday of September in AU. Promote dad/family sessions and instant gift vouchers for last-minute gifters.",
    tags: ["fathers day", "family"] },
  { id: "sep-spring-refresh", title: "Spring brand-refresh campaign", category: "offers", months: [9],
    effort: "medium", cost: "low", impact: "high",
    description: "Spring = renewal. Promote refreshed personal-branding galleries for the busy end-of-year business and event season ahead.",
    tags: ["spring", "personal branding"] },
  { id: "sep-spring-minis", title: "Spring mini-session day", category: "offers", months: [9, 10],
    effort: "medium", cost: "low", impact: "high",
    description: "Batch a day of short, lower-priced sessions to fill the calendar and introduce new clients to the Henley experience.",
    tags: ["mini session", "spring"] },

  // ---- OCTOBER (Spring) -------------------------------------------------
  { id: "oct-spring-racing", title: "Spring Racing Carnival glam shoot", category: "offers", months: [10],
    effort: "medium", cost: "low", impact: "medium",
    description: "Tie into Melbourne Cup / race-day fashion. Offer glamorous portrait sessions — fascinators, frocks, full hair & makeup.",
    tags: ["glam", "spring racing", "event"] },
  { id: "oct-bf-warmup", title: "Build a Black Friday VIP list", category: "email", months: [10],
    effort: "low", cost: "low", impact: "high",
    description: "Start a waitlist for your Black Friday voucher deal. Early-access subscribers convert far better when the offer drops.",
    tags: ["black friday", "list building"] },
  { id: "oct-eoy-events", title: "“Headshot before your end-of-year events” push", category: "social", months: [10, 11],
    effort: "low", cost: "free", impact: "medium",
    description: "Awards nights, conferences and Christmas parties are coming — prompt professionals to update their image before being seen.",
    tags: ["headshots", "events"] },

  // ---- NOVEMBER (Spring) ------------------------------------------------
  { id: "nov-black-friday", title: "Black Friday / Cyber Monday voucher sale", category: "offers", months: [11],
    effort: "high", cost: "medium", impact: "high",
    description: "Your biggest sales moment. Offer limited gift vouchers or session bundles with bonus credit. Plan email + retargeting weeks ahead.",
    tags: ["black friday", "gift voucher", "sale"] },
  { id: "nov-gift-voucher-launch", title: "Launch Christmas gift-voucher season", category: "offers", months: [11],
    effort: "medium", cost: "low", impact: "high",
    description: "Position a Henley Studio session as the ultimate Christmas gift. Beautiful printable/instant vouchers, promoted across every channel.",
    tags: ["gift voucher", "christmas"] },
  { id: "nov-party-headshots", title: "Party-season personal-branding refresh", category: "paid", months: [11],
    effort: "medium", cost: "medium", impact: "medium",
    description: "Run targeted ads to Brisbane professionals: look your best for end-of-year networking, LinkedIn, and the new year ahead.",
    tags: ["paid", "professionals"] },

  // ---- DECEMBER (Summer · Christmas) -----------------------------------
  { id: "dec-last-min-vouchers", title: "Last-minute instant gift vouchers", category: "offers", months: [12],
    effort: "low", cost: "low", impact: "high",
    description: "Capture Christmas procrastinators with instantly-delivered digital vouchers. Promote shipping/print cut-off dates for urgency.",
    tags: ["gift voucher", "christmas"] },
  { id: "dec-family-summer", title: "Summer family / extended-family sessions", category: "offers", months: [12, 1],
    effort: "medium", cost: "low", impact: "medium",
    description: "Relatives are in town over the AU summer holidays — a rare chance for generational portraits. Promote limited holiday session slots.",
    tags: ["family", "summer", "christmas"] },
  { id: "dec-year-in-review", title: "Share a 'year of clients' highlight reel", category: "video", months: [12],
    effort: "medium", cost: "free", impact: "medium",
    description: "A heartfelt montage of your favourite transformations and sessions this year. Celebrates clients and showcases your range.",
    tags: ["recap", "social proof"] },

  // ---- EVERGREEN: Social & Video ---------------------------------------
  { id: "ever-transformation", title: "Post before/after transformation reveals", category: "social", months: [],
    effort: "low", cost: "free", impact: "high",
    description: "Your single strongest content: everyday arrival → hair, makeup & guided posing → stunning final image. Stops the scroll and sells the experience.",
    tags: ["transformation", "social proof"] },
  { id: "ever-bts-reels", title: "Behind-the-scenes session reels", category: "video", months: [],
    effort: "low", cost: "free", impact: "high",
    description: "Show the luxury experience in action — the studio, MUA, posing guidance, client reactions. Reels are your top organic reach channel.",
    tags: ["reels", "behind the scenes"] },
  { id: "ever-posing-tips", title: "Posing & confidence tips series", category: "video", months: [],
    effort: "medium", cost: "free", impact: "medium",
    description: "Short videos easing the #1 fear — 'I'm not photogenic'. Positions you as the guide who makes anyone look incredible.",
    tags: ["education", "reels", "confidence"] },
  { id: "ever-client-reveal-reaction", title: "Capture & share client reveal reactions", category: "video", months: [],
    effort: "low", cost: "free", impact: "high",
    description: "Film genuine reactions at the gallery reveal. Emotional, authentic proof that converts far better than the photos alone.",
    tags: ["social proof", "reveal"] },
  { id: "ever-studio-tour", title: "Showcase the studio & experience", category: "social", months: [],
    effort: "low", cost: "free", impact: "medium",
    description: "A tour of the space, wardrobe, and hair-and-makeup setup. Builds trust and sets Henley Studio apart from at-home shooters.",
    tags: ["studio", "experience", "USP"] },

  // ---- EVERGREEN: Reviews, Referrals & Client Experience ---------------
  { id: "ever-google-reviews", title: "Systematise Google review requests", category: "client", months: [],
    effort: "low", cost: "free", impact: "high",
    description: "Ask every delighted client for a Google review right after the reveal. Drives both trust and local Brisbane search ranking.",
    tags: ["reviews", "local SEO"] },
  { id: "ever-testimonials", title: "Collect video & written testimonials", category: "client", months: [],
    effort: "low", cost: "free", impact: "high",
    description: "Capture a quick quote or clip while clients are glowing post-reveal. Sprinkle proof across your site, ads, and socials.",
    tags: ["social proof", "testimonials"] },
  { id: "ever-referral-program", title: "Launch a refer-a-friend program", category: "referral", months: [],
    effort: "medium", cost: "low", impact: "high",
    description: "Reward clients who refer with print credit or a free upgrade for both parties. Photography thrives on word of mouth.",
    tags: ["referral", "word of mouth"] },
  { id: "ever-annual-club", title: "Annual headshot refresh club", category: "referral", months: [],
    effort: "medium", cost: "low", impact: "high",
    description: "A loyalty offer for professionals to update their headshots yearly at a member rate. Predictable repeat revenue.",
    tags: ["loyalty", "repeat", "headshots"] },
  { id: "ever-reactivate-past", title: "Reactivate past clients for a refresh", category: "email", months: [],
    effort: "low", cost: "free", impact: "high",
    description: "Email clients from 12–18 months ago: outfits, brands and faces change — time to refresh. Cheapest booking you'll ever get.",
    tags: ["retention", "reactivation"] },
  { id: "ever-wall-art-upsell", title: "Promote wall art & print products", category: "client", months: [],
    effort: "medium", cost: "low", impact: "high",
    description: "Show stunning framed prints and albums in-studio and online. Raises average order value well beyond the session fee.",
    tags: ["IPS", "prints", "upsell"] },

  // ---- EVERGREEN: Partnerships & Local ---------------------------------
  { id: "ever-mua-collab", title: "Collaborate with MUAs, hair & stylists", category: "partnerships", months: [],
    effort: "medium", cost: "low", impact: "medium",
    description: "Cross-promote with the beauty pros you work with. Styled content for both, plus referrals from their client base.",
    tags: ["collab", "beauty", "referral"] },
  { id: "ever-boutique-collab", title: "Partner with local fashion boutiques", category: "partnerships", months: [],
    effort: "medium", cost: "low", impact: "medium",
    description: "Co-create styled shoots with Brisbane boutiques — they get product imagery, you reach their style-conscious customers.",
    tags: ["collab", "fashion", "local"] },
  { id: "ever-business-networking", title: "Join a Brisbane networking group", category: "community", months: [],
    effort: "medium", cost: "medium", impact: "high",
    description: "BNI, chambers, women-in-business groups — personal-branding clients are business owners. Be the photographer they all know.",
    tags: ["networking", "B2B", "local"] },
  { id: "ever-coworking-headshots", title: "Pop-up headshot days at coworking spaces", category: "partnerships", months: [],
    effort: "high", cost: "medium", impact: "high",
    description: "Partner with Brisbane coworking hubs for a headshot pop-up. Concentrated access to exactly your target market.",
    tags: ["headshots", "B2B", "local"] },
  { id: "ever-podcast-guest", title: "Guest on local business podcasts", category: "pr", months: [],
    effort: "medium", cost: "free", impact: "medium",
    description: "Talk personal branding & visibility on Brisbane business shows. Borrow their audience of potential branding clients.",
    tags: ["PR", "personal branding"] },
  { id: "ever-charity-auction", title: "Donate a session to a local charity auction", category: "pr", months: [],
    effort: "low", cost: "low", impact: "medium",
    description: "Gift a luxury session to a Brisbane fundraiser. Goodwill, brand exposure to an affluent audience, and a portfolio opportunity.",
    tags: ["charity", "local", "PR"] },

  // ---- EVERGREEN: Website, SEO & Email ---------------------------------
  { id: "ever-gbp", title: "Optimise your Google Business Profile", category: "seo", months: [],
    effort: "low", cost: "free", impact: "high",
    description: "Highest-leverage free move for a local studio: complete profile, fresh photos, weekly posts, and reviews. Wins 'photographer near me'.",
    tags: ["local SEO", "free"] },
  { id: "ever-local-seo-pages", title: "Write location & service SEO pages", category: "seo", months: [],
    effort: "high", cost: "free", impact: "high",
    description: "Target 'personal branding photographer Brisbane', 'Brisbane headshots', 'boudoir photographer Brisbane'. Evergreen organic leads.",
    tags: ["SEO", "local", "Brisbane"] },
  { id: "ever-blog-sessions", title: "Blog each session as a story", category: "content", months: [],
    effort: "medium", cost: "free", impact: "medium",
    description: "Feature client sessions with their story + best images. Fresh SEO content, social proof, and clients love being featured (= shares).",
    tags: ["blog", "SEO", "social proof"] },
  { id: "ever-pinterest", title: "Build Pinterest 'what to wear' boards", category: "content", months: [],
    effort: "low", cost: "free", impact: "medium",
    description: "Pinterest drives long-tail traffic for styling and outfit inspo — and quietly funnels planners toward booking you.",
    tags: ["pinterest", "styling", "SEO"] },
  { id: "ever-lead-magnet", title: "Create a session-planning lead magnet", category: "content", months: [],
    effort: "medium", cost: "free", impact: "high",
    description: "A free 'how to prepare for your branding shoot' or 'what to wear' guide in exchange for an email. Grows your nurture list.",
    tags: ["lead magnet", "email", "styling"] },
  { id: "ever-enquiry-nurture", title: "Automate an enquiry nurture sequence", category: "email", months: [],
    effort: "medium", cost: "low", impact: "high",
    description: "Not everyone books on first contact. A 3–4 email sequence with proof, FAQs and the experience warms leads until they're ready.",
    tags: ["automation", "leads", "nurture"] },
  { id: "ever-newsletter", title: "Send a regular studio newsletter", category: "email", months: [],
    effort: "medium", cost: "free", impact: "medium",
    description: "Stay top of mind with recent sessions, tips, and offers. An owned audience you control — not at the mercy of the algorithm.",
    tags: ["email", "owned media"] },

  // ---- EVERGREEN: Paid & Offers ----------------------------------------
  { id: "ever-retargeting", title: "Run retargeting ads to site visitors", category: "paid", months: [],
    effort: "medium", cost: "medium", impact: "high",
    description: "People research photographers before booking. Retarget website/Instagram visitors with your best work — usually the highest-ROAS ad.",
    tags: ["paid", "retargeting", "ROAS"] },
  { id: "ever-lead-ads", title: "Test Meta lead-gen ads for sessions", category: "paid", months: [],
    effort: "medium", cost: "medium", impact: "medium",
    description: "Targeted ads to Brisbane professionals or women for personal branding / boudoir, driving to a waitlist or enquiry form.",
    tags: ["paid", "lead gen", "Meta"] },
  { id: "ever-corporate-packages", title: "Build a corporate headshot package sheet", category: "offers", months: [],
    effort: "medium", cost: "free", impact: "high",
    description: "A clear, ready-to-send package for teams (per-person pricing, on-site or studio). Makes it easy for businesses to say yes.",
    tags: ["corporate", "B2B", "packages"] },
  { id: "ever-styled-shoot", title: "Host a styled shoot to build portfolio", category: "offers", months: [],
    effort: "high", cost: "medium", impact: "medium",
    description: "Collaborate with stylists, MUAs and models on a creative concept. Refreshes your portfolio and generates content for everyone.",
    tags: ["portfolio", "collab", "content"] },
];
